### ISSUE TITLE
 wrong lunar version

### ISSUE THREAD

**Issue by deadchoco** [Solar-Tweaks/SolarTweaks-Mappings#4]
I am getting the error wrong lunar version
And i have  mappings a1f71bc but threre is no mappings files of a1f71bc
![Lunar Client (1 8 9-a1f71bc_master) 2022-02-13 오후 11_17_38](https://user-images.githubusercontent.com/68216675/153757292-629032e6-9572-4dbb-ba21-a048aaa5f13e.png)

**Comment by Brafun-dot** [comment]
same

**Comment by HKS-HNS** [comment]
Should I create one?

**Comment by deadchoco** [comment]
finally I made it
